name: CI/CD to AWS

on:
  push:
    branches:
     - release


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install -y maven

    - name: Build Project
      run: |
        mvn install
        ls -l target

    - name: Add SSH Key
      run: |
        echo "${{ secrets.AWS_PEM_KEY }}" > /home/runner/aws_key.pem
        chmod 400 /home/runner/aws_key.pem

    - name: Deploy to EC2
      env:
        WAR_FILE: target/emotiondiary.war
      run: |
        echo test
        ls -l /home/runner
        scp -i /home/runner/aws_key.pem $WAR_FILE ec2-user@ec2-13-125-55-125.ap-northeast-2.compute.amazonaws.com:/home/ec2-user